spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enable: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

redis:
  database: Erlik-free-db
  password: pHFiSNfeqNPVfFDNugWCnNF0FuQ0PgVx
  host: redis-19221.c81.us-east-1-2.ec2.cloud.redislabs.com
  port: 19221
